default:
  image: node:20

stages:
  - install
  - eslint
  - prettier
  
install:
  stage: install
  script:
    - echo 'Install dependencies...'
    - npm ci
  artifacts:
    paths:
    - node_modules/
    expire_in: 1h


eslint:
  stage: eslint
  script:
    - echo 'Run ESlint...'
    - npm run lint

prettier:
  stage: prettier
  script:
    - echo 'Run Prettier...'
    - npm run prettier
