default:
  image: node:20

stages:
  - install
  - build
  - validate

install:
  stage: install
  script:
    - echo 'install dependencies...'

build:
  stage: build
  script:
    - echo 'building project...'

validate:
  stage: validate
  script:
    - echo 'validation...'
