default:
  image: node:20

stages:
  - install
  - build-deploy
  
install:
  stage: install
  script:
    - echo 'Install dependencies...'
    - npm ci
  artifacts:
    paths:
    - node_modules/
    expire_in: 1h

build-deploy:
  stage: build-deploy
  only:
    - master
  script:
    - echo 'Build Project...'
    - npm run build
  artifacts:
   paths:
    - build/notes-list-app/browser
   expire_in: 1h
  dependencies:
    - install