default:
  image: node:20

stages:
  - install
  - build
  - deploy
  
install:
  stage: install
  script:
    - echo 'Install dependencies...'
    - npm ci
  artifacts:
    paths:
    - node_modules/
    expire_in: 1h

build:
  stage: build
  script:
    - echo 'Build Project...'
    - npm run build
  artifacts:
   paths:
    - dist/
   expire_in: 1h
  dependencies:
    - install

pages:
  stage: deploy
  script:
    - echo 'Deploying on GL Pages...'
    - cp -r dist/notes-list-app/browser/* public/
  artifacts:
   paths:
    - public/
   expire_in: 1h
  dependencies:
    - install
    - build
